language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.2
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text

notifications:
    email: false
